### ISSUE TITLE
instance routes checklist

### ISSUE THREAD

**Issue by vinibgoulart** [salman0ansari/whatsapp-api-nodejs#617]
instance routes has some fix:
- [ ] delete instance not working
- [ ] error always return false
- [ ] prefer early return instead `else`
- [ ] qrcode catch return missing data
- [ ] instance info catch must return `data: null` instead `{}`

**Comment by salman0ansari** [comment]
will be fixed in #486

**Comment by vinibgoulart** [comment]
how can i contribute?

**Comment by salman0ansari** [comment]
> how can i contribute?

clone and switch branch
